// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type RemoteServer struct {
	Name     string `json:"name"`
	Hostport string `json:"hostport"`
	Secret   string `json:"secret"`
}
