// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type RemoteServer struct {
	Name     string `json:"name"`
	Hostport string `json:"hostport"`
	Secret   string `json:"secret"`
}

type User struct {
	Name       string `json:"name"`
	Active     bool   `json:"active"`
	Superuser  bool   `json:"superuser"`
	TotpSecret string `json:"totp_secret"`
}
