// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const addRemoteServer = `-- name: AddRemoteServer :exec
INSERT INTO remote_servers (name, hostport, secret) VALUES (?, ?, ?)
`

type AddRemoteServerParams struct {
	Name     string `json:"name"`
	Hostport string `json:"hostport"`
	Secret   string `json:"secret"`
}

func (q *Queries) AddRemoteServer(ctx context.Context, arg AddRemoteServerParams) error {
	_, err := q.db.ExecContext(ctx, addRemoteServer, arg.Name, arg.Hostport, arg.Secret)
	return err
}

const addUser = `-- name: AddUser :exec
INSERT INTO users (name, active, superuser, totp_secret) VALUES (?, ?, ?, ?)
`

type AddUserParams struct {
	Name       string `json:"name"`
	Active     bool   `json:"active"`
	Superuser  bool   `json:"superuser"`
	TotpSecret string `json:"totp_secret"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser,
		arg.Name,
		arg.Active,
		arg.Superuser,
		arg.TotpSecret,
	)
	return err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET active = false WHERE name = ?
`

func (q *Queries) DeactivateUser(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deactivateUser, name)
	return err
}

const deleteRemoteServer = `-- name: DeleteRemoteServer :exec
DELETE FROM remote_servers WHERE name = ?
`

func (q *Queries) DeleteRemoteServer(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRemoteServer, name)
	return err
}

const getRemoteServer = `-- name: GetRemoteServer :one
SELECT name, hostport, secret FROM remote_servers WHERE name = ?
`

func (q *Queries) GetRemoteServer(ctx context.Context, name string) (RemoteServer, error) {
	row := q.db.QueryRowContext(ctx, getRemoteServer, name)
	var i RemoteServer
	err := row.Scan(&i.Name, &i.Hostport, &i.Secret)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT name, active, superuser, totp_secret FROM users WHERE name = ?
`

func (q *Queries) GetUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.Name,
		&i.Active,
		&i.Superuser,
		&i.TotpSecret,
	)
	return i, err
}

const listRemoteServers = `-- name: ListRemoteServers :many
SELECT name, hostport, secret FROM remote_servers
`

func (q *Queries) ListRemoteServers(ctx context.Context) ([]RemoteServer, error) {
	rows, err := q.db.QueryContext(ctx, listRemoteServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteServer
	for rows.Next() {
		var i RemoteServer
		if err := rows.Scan(&i.Name, &i.Hostport, &i.Secret); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT name, active, superuser, totp_secret FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Name,
			&i.Active,
			&i.Superuser,
			&i.TotpSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemoteServer = `-- name: UpdateRemoteServer :exec
UPDATE remote_servers SET name = ?, hostport = ?, secret = ? WHERE name = ?
`

type UpdateRemoteServerParams struct {
	Name     string `json:"name"`
	Hostport string `json:"hostport"`
	Secret   string `json:"secret"`
	Name_2   string `json:"name_2"`
}

func (q *Queries) UpdateRemoteServer(ctx context.Context, arg UpdateRemoteServerParams) error {
	_, err := q.db.ExecContext(ctx, updateRemoteServer,
		arg.Name,
		arg.Hostport,
		arg.Secret,
		arg.Name_2,
	)
	return err
}
