
-- ========================================
-- Migration: 0001_initial
-- ========================================

BEGIN;
--
-- Create model Machine
--
CREATE TABLE "console_machine" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(64) NOT NULL, "hostport" varchar(512) NOT NULL, "secret_key" varchar(256) NOT NULL);
COMMIT;

-- ========================================
-- Migration: 0002_remove_machine_id_alter_machine_name
-- ========================================

BEGIN;
--
-- Remove field id from machine
--
ALTER TABLE "console_machine" DROP COLUMN "id";
--
-- Alter field name on machine
--
ALTER TABLE "console_machine" ADD CONSTRAINT "console_machine_name_952157a7_pk" PRIMARY KEY ("name");
CREATE INDEX "console_machine_name_952157a7_like" ON "console_machine" ("name" varchar_pattern_ops);
COMMIT;

-- ========================================
-- Migration: 0003_vmsession
-- ========================================

BEGIN;
--
-- Create model VMSession
--
CREATE TABLE "console_vmsession" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "vm_name" varchar(64) NOT NULL, "session_id" varchar(36) NOT NULL UNIQUE, "created_at" timestamp with time zone NOT NULL, "machine_id" varchar(64) NOT NULL);
ALTER TABLE "console_vmsession" ADD CONSTRAINT "console_vmsession_machine_id_acbc5ad1_fk_console_machine_name" FOREIGN KEY ("machine_id") REFERENCES "console_machine" ("name") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "console_vmsession_session_id_12cb8f54_like" ON "console_vmsession" ("session_id" varchar_pattern_ops);
CREATE INDEX "console_vmsession_machine_id_acbc5ad1" ON "console_vmsession" ("machine_id");
CREATE INDEX "console_vmsession_machine_id_acbc5ad1_like" ON "console_vmsession" ("machine_id" varchar_pattern_ops);
COMMIT;

-- ========================================
-- Migration: 0004_vmsession_claimed
-- ========================================

BEGIN;
--
-- Add field claimed to vmsession
--
ALTER TABLE "console_vmsession" ADD COLUMN "claimed" boolean DEFAULT false NOT NULL;
ALTER TABLE "console_vmsession" ALTER COLUMN "claimed" DROP DEFAULT;
COMMIT;

-- ========================================
-- Migration: 0005_vmsession_claimed_by
-- ========================================

BEGIN;
--
-- Add field claimed_by to vmsession
--
ALTER TABLE "console_vmsession" ADD COLUMN "claimed_by" varchar(256) NULL;
COMMIT;

-- ========================================
-- Migration: 0006_notification
-- ========================================

BEGIN;
--
-- Create model Notification
--
CREATE TABLE "console_notification" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(256) NOT NULL, "message" text NOT NULL, "read" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
COMMIT;

-- ========================================
-- Migration: 0007_deployment
-- ========================================

BEGIN;
--
-- Create model Deployment
--
CREATE TABLE "console_deployment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(256) NOT NULL, "replicas_desired" integer NOT NULL, "service_name" varchar(256) NULL);
COMMIT;

-- ========================================
-- Migration: 0008_delete_notification
-- ========================================

BEGIN;
--
-- Delete model Notification
--
DROP TABLE "console_notification" CASCADE;
COMMIT;

-- ========================================
-- Migration: 0009_automation
-- ========================================

BEGIN;
--
-- Create model Automation
--
CREATE TABLE "console_automation" ("automation_id" varchar(36) NOT NULL PRIMARY KEY, "json_data" jsonb NOT NULL);
CREATE INDEX "console_automation_automation_id_89f0e948_like" ON "console_automation" ("automation_id" varchar_pattern_ops);
COMMIT;

-- ========================================
-- Migration: 0010_auditlog
-- ========================================

BEGIN;
--
-- Create model AuditLog
--
CREATE TABLE "console_auditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(256) NOT NULL, "detail" text NOT NULL, "ipaddr" varchar(1024) NOT NULL, "timestamp" timestamp with time zone NOT NULL, "user_id" integer NULL);
ALTER TABLE "console_auditlog" ADD CONSTRAINT "console_auditlog_user_id_28147314_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "console_auditlog_user_id_28147314" ON "console_auditlog" ("user_id");
COMMIT;
