# this entire file was generated by AI
#!/usr/bin/env bash

# Output file path
OUTPUT_FILE="all_migrations.sql"

# Clear or create the output file
> "$OUTPUT_FILE"

# Path to migrations directory
MIGRATION_DIR="frontend/console/migrations"

# Check if migration directory exists
if [ ! -d "$MIGRATION_DIR" ]; then
  echo "Error: Directory '$MIGRATION_DIR' not found."
  exit 1
fi

echo "Generating SQL for migrations..."

# Loop over each .py file in the migrations folder (excluding __init__.py)
for filepath in "$MIGRATION_DIR"/[0-9]*.py; do
  # Check if matching files exist
  [ -e "$filepath" ] || continue

  # Extract just the file name without path and extension (e.g., "0001_initial")
  filename=$(basename "$filepath" .py)

  echo "Processing migration: $filename"

  # Add a visual header comment in the output SQL file
  echo -e "\n-- ========================================" >> "$OUTPUT_FILE"
  echo "-- Migration: $filename" >> "$OUTPUT_FILE"
  echo -e "-- ========================================\n" >> "$OUTPUT_FILE"

  # Run sqlmigrate and append output
  python frontend/manage.py sqlmigrate console "$filename" >> "$OUTPUT_FILE"
done

echo -e "\nDone! All SQL statements compiled into '$OUTPUT_FILE'."