#!/usr/bin/env bash
# this entire file was generated by AI

OUTPUT_FILE="all_migrations.sql"
> "$OUTPUT_FILE"

echo "Extracting migration list across all apps..."

# Uses python manage.py showmigrations --plan to reliably get:
# <app_label> <migration_name>
$CONSOLE_PYTHON frontend/manage.py showmigrations --plan | awk '/^\[/ {print $2, $3}' | while read -r app migration; do
  
  # Skip if app or migration name is empty
  [ -z "$app" ] || [ -z "$migration" ] && continue

  echo "Processing: $app -> $migration"

  # Add visual section headers
  echo -e "\n-- ========================================" >> "$OUTPUT_FILE"
  echo "-- App: $app | Migration: $migration" >> "$OUTPUT_FILE"
  echo -e "-- ========================================\n" >> "$OUTPUT_FILE"

  # Append SQL output
  $CONSOLE_PYTHON frontend/manage.py sqlmigrate "$app" "$migration" >> "$OUTPUT_FILE"
done

echo -e "\nDone! Saved all migration SQL into '$OUTPUT_FILE'."