package main

import (
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/labstack/echo/v4"
	"github.com/shirou/gopsutil/v4/net"
	"github.com/shirou/gopsutil/v4/process"
	"github.com/tiredkangaroo/mechanicaldinosaurs/daemon/vms"
	"github.com/tiredkangaroo/mechanicaldinosaurs/server"
)

func main() {
	e := echo.New()
	auth := Auth{Secret: API_SECRET}
	api := e.Group("", auth.Middleware)

	server.Handle(api, server.GetInfoRequest, func(c echo.Context, req struct{}) (*server.Info, error) {
		info, err := GetServerInfo()
		if err != nil {
			return nil, err
		}
		return info, nil
	})

	server.Handle(api, server.GetPortsServicesRequest, func(c echo.Context, req struct{}) (*map[uint32]string, error) {
		// most of the code from this function was generated by ai
		connections, err := net.Connections("all")
		if err != nil {
			return nil, err
		}
		res := make(map[uint32]string)
		seen := make(map[string]bool)
		for _, conn := range connections {
			if conn.Status != "LISTEN" && (conn.Type == 2 && conn.Status == "NONE") { // not tcp listen or udp sockets
				continue
			}
			port := conn.Laddr.Port
			proto := "tcp"
			if conn.Type == 2 { // sock_dgram
				proto = "udp"
			}

			key := fmt.Sprintf("%s:%d", proto, port)
			if seen[key] {
				continue
			}
			seen[key] = true

			// skip placeholders
			if conn.Pid <= 0 {
				continue
			}

			// get process details from the pid
			proc, err := process.NewProcess(conn.Pid)
			var cmdName string
			if err != nil {
				cmdName = "Unknown (Terminated)"
			} else {
				// verbose name or fallblback if Name() fails
				cmdName, err = proc.Name()
				if err != nil {
					cmdName, _ = proc.Cmdline()
				}
			}
			res[port] = cmdName
		}
		return &res, nil
	})

	registerVMRoutes(api)
	registerTunnelRoutes(api)

	slog.Info("starting server", "port", PORT)
	if err := e.Start(":" + PORT); err != nil {
		slog.Error("server error", "error", err)
	}
}

func registerVMRoutes(api *echo.Group) {
	available, err := vms.Available()
	if err != nil {
		slog.Error("check VM availability", "error", err)
	}

	vmRouter := api.Group("", func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			if !available {
				return c.JSON(503, map[string]string{"error": "vm functionality not available on this host"})
			}
			return next(c)
		}
	})

	server.Handle(vmRouter, server.GetVMAvailableRequest, func(c echo.Context, req struct{}) (*struct{}, error) {
		return nil, nil // middleware handles here
	})

	server.Handle(vmRouter, server.ListVMsRequest, func(c echo.Context, req struct{}) (*[]server.VM, error) {
		machines, err := vms.ListVMs()
		if err != nil {
			return nil, err
		}
		return &machines, nil
	})

	server.Handle(vmRouter, server.AvailableBootFilesRequest, func(c echo.Context, req struct{}) (*[]string, error) {
		entries, err := os.ReadDir(filepath.Join(MECHANICAL_DINOSAURS_DATA, "boot_files"))
		if err != nil {
			return nil, err
		}
		var files []string
		for _, entry := range entries {
			if !entry.IsDir() {
				files = append(files, entry.Name())
			}
		}
		return &files, nil
	})

	server.Handle(vmRouter, server.CreateVMRequest, func(c echo.Context, req server.VMConfig) (*struct{}, error) {
		_, err := vms.CreateVM(&req)
		if err != nil {
			return nil, err
		}
		return nil, nil
	})

	server.Handle(vmRouter, server.GetVMRequest, func(c echo.Context, req struct{}) (*server.VM, error) {
		name := c.QueryParam("name")
		if name == "" {
			return nil, echo.NewHTTPError(400, "missing query parameter: name")
		}
		vm, err := vms.GetVM(name)
		return &vm, err
	})

	server.Handle(vmRouter, server.StartVMRequest, func(c echo.Context, req server.VMTargetReq) (*struct{}, error) {
		if err := vms.StartVM(req.Name); err != nil {
			return nil, err
		}
		return nil, nil
	})

	server.Handle(vmRouter, server.StopVMRequest, func(c echo.Context, req server.VMTargetReq) (*struct{}, error) {
		forcefulStr := c.QueryParam("force")
		forceful := forcefulStr == "true"
		if err := vms.StopVM(req.Name, !forceful); err != nil {
			return nil, err
		}
		return nil, nil
	})

	server.Handle(vmRouter, server.RestartVMRequest, func(c echo.Context, req server.VMTargetReq) (*struct{}, error) {
		forcefulStr := c.QueryParam("force")
		forceful := forcefulStr == "true"
		if err := vms.RestartVM(req.Name, !forceful); err != nil {
			return nil, err
		}
		return nil, nil
	})

	server.Handle(vmRouter, server.UpdateVMRequest, func(c echo.Context, req server.UpdateVMReq) (*struct{}, error) {
		if err := vms.UpdateVM(req.Name, req.VCPUs, req.MemoryMiB, req.StorageGiB); err != nil {
			return nil, err
		}
		return nil, nil
	})

	server.Handle(vmRouter, server.DeleteVMRequest, func(c echo.Context, req server.VMTargetReq) (*struct{}, error) {
		if err := vms.DeleteVM(req.Name); err != nil {
			return nil, err
		}
		return nil, nil
	})

	server.Handle(vmRouter, server.DownloadISORequest, func(c echo.Context, req server.DownloadISOReq) (*struct{}, error) {
		downloadURL := req.URL
		switch req.OSName {
		case "ubuntu-desktop":
			if runtime.GOARCH != "amd64" {
				return nil, fmt.Errorf("ubuntu-desktop is only available for amd64 architecture")
			}
			downloadURL = fmt.Sprintf("https://mirror.pilotfiber.com/ubuntu-iso/%s/ubuntu-%s-desktop-amd64.iso", req.Version, req.Version)
		case "ubuntu-server":
			if runtime.GOARCH != "amd64" {
				return nil, fmt.Errorf("ubuntu-server is only available for amd64 architecture")
			}
			downloadURL = fmt.Sprintf("https://mirror.pilotfiber.com/ubuntu-iso/%s/ubuntu-%s-live-server-amd64.iso", req.Version, req.Version)
		case "debian":
			downloadURL = fmt.Sprintf("https://cdimage.debian.org/debian-cd/%s/%s/iso-cd/debian-%s-%s-netinst.iso", req.Version, runtime.GOARCH, req.Version, runtime.GOARCH)
		}
		if downloadURL == "" {
			return nil, fmt.Errorf("download URL could not be determined and no download URL provided (os/version: %s/%s on arch: %s)", req.OSName, req.Version, runtime.GOARCH)
		}
		// download the ISO to $MECHANICAL_DINOSAURS_DATA/boot_files
		var isoName string
		if req.OSName == "" {
			u, err := url.Parse(downloadURL)
			if err != nil {
				return nil, fmt.Errorf("download URL not parseable: %s", downloadURL)
			}
			pathSplit := strings.Split(u.Path, "/")
			isoName = pathSplit[len(pathSplit)-1]
			if isoName == "" { // no path?!
				isoName = fmt.Sprintf("iso-downloaded-from-%s.iso", u.Host)
			}
		} else {
			isoName = fmt.Sprintf("%s-%s.iso", req.OSName, req.Version)
		}

		file, err := os.OpenFile(filepath.Join(MECHANICAL_DINOSAURS_DATA, "boot_files", isoName), os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			return nil, fmt.Errorf("opening file: %v", err)
		}
		defer file.Close()

		resp, err := http.Get(downloadURL)
		if err != nil {
			return nil, fmt.Errorf("downloading ISO: %v", err)
		}

		go func(resp *http.Response) {
			defer resp.Body.Close()
			// copy the downloaded content to the file
			_, err = io.Copy(file, resp.Body)
			if err != nil {
				slog.Error("error copying ISO", "error", err)
			} else {
				slog.Info("iso download complete", "file", isoName)
			}
		}(resp)

		return nil, nil
	})

	vmRouter.GET("/api/vms/:name/proxy", func(c echo.Context) error {
		name := c.Param("name")
		if name == "" {
			return echo.NewHTTPError(400, "missing path parameter: name")
		}
		conn, _, err := c.Response().Hijack()
		if err != nil {
			return echo.NewHTTPError(500, "failed to hijack connection")
		}
		defer conn.Close()
		return vms.ProxyVM(name, conn)
	})
}

func registerTunnelRoutes(api *echo.Group) {
	server.Handle(api, server.GetCloudflareTunnelTokenRequest, func(c echo.Context, req struct{}) (*[]server.CloudflareTunnelIDorTokenResponse, error) {
		resp := []server.CloudflareTunnelIDorTokenResponse{}

		// list $HOME/.cloudflared and get the tunnel ids from filenames
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return nil, err
		}
		tunnelDir := filepath.Join(homeDir, ".cloudflared")
		files, err := os.ReadDir(tunnelDir)
		if err == nil {
			for _, file := range files {
				if !file.IsDir() && filepath.Ext(file.Name()) == ".json" {
					tunnelID := file.Name()[:len(file.Name())-len(".json")]
					resp = append(resp, server.CloudflareTunnelIDorTokenResponse{
						Type:  "id",
						Value: tunnelID,
					})
				}
			}
		}

		// get the token from the running cloudflared process
		cmd := exec.Command("bash", "-c", "ps aux | grep cloudflared | grep -v grep | awk '{print $NF}' | sed 's/--token //g'")
		data, err2 := cmd.Output()
		if err == nil || err2 == nil {
			resp = append(resp, server.CloudflareTunnelIDorTokenResponse{
				Type:  "token",
				Value: string(data),
			})
		}

		return &resp, nil
	})
}
