# Generated by Django 6.0.6 on 2026-06-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hostport', models.CharField(max_length=512)),
                ('secret_key', models.CharField(max_length=256)),
            ],
        ),
    ]
