# Generated by Django 6.0.6 on 2026-06-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_remove_machine_id_alter_machine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=64)),
                ('session_id', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.machine')),
            ],
        ),
    ]
