# Generated by Django 6.0.6 on 2026-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_vmsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmsession',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
