# Generated by Django 6.0.6 on 2026-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_vmsession_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmsession',
            name='claimed_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
