# Generated by Django 6.0.6 on 2026-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_vmsession_claimed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
