# Generated by Django 6.0.6 on 2026-07-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('replicas_desired', models.IntegerField()),
                ('service_name', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
