# Generated by Django 6.0.6 on 2026-07-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_deployment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
