# Generated by Django 6.0.6 on 2026-07-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('automation_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('json_data', models.JSONField()),
            ],
        ),
    ]
