# Generated by Django 6.0.6 on 2026-08-19 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36, unique=True)),
                ('proxy_url', models.CharField(max_length=512)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_by', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.machine')),
            ],
        ),
        migrations.DeleteModel(
            name='VMSession',
        ),
    ]
