# Generated by Django 6.0.6 on 2026-08-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_proxysession_delete_vmsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxysession',
            name='initial_req_is_http',
            field=models.BooleanField(default=True),
        ),
    ]
