# Generated by Django 6.0.6 on 2026-08-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_proxysession_initial_req_is_http'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cf_tunnel_ids',
            field=models.CharField(blank=True, max_length=1331, null=True),
        ),
    ]
