# Generated by Django 6.0.6 on 2026-08-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_machine_cf_tunnel_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='cf_tunnel_ids',
        ),
        migrations.AddField(
            model_name='machine',
            name='cf_tunnels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
